package com.esspl.hemendra.mydaogenerator.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.esspl.hemendra.mydaogenerator.Person;
import com.esspl.hemendra.mydaogenerator.Test;

import com.esspl.hemendra.mydaogenerator.dao.PersonDao;
import com.esspl.hemendra.mydaogenerator.dao.TestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig testDaoConfig;

    private final PersonDao personDao;
    private final TestDao testDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        testDao = new TestDao(testDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Test.class, testDao);
    }
    
    public void clear() {
        personDaoConfig.getIdentityScope().clear();
        testDaoConfig.getIdentityScope().clear();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public TestDao getTestDao() {
        return testDao;
    }

}
